### ISSUE TITLE
Fix 'VkPhysicalDeviceVulkan13Features' case in combination script

### ISSUE THREAD

**Issue by christophe-lunarg** [KhronosGroup/Vulkan-Profiles#223]
```
If I choose a base profile to be Adreno which doesn't have VkPhysicalDeviceVulkan13Features, and secondary to be Radeon which has VkPhysicalDeviceVulkan13Features, it causes the following exception:
Traceback (most recent call last):
  File "/combine_profiles.py", line 579, in <module>
    profile_merger.merge(jsons, profiles, profile_names, args.output_path, args.output_profile, args.mode)
  File "/combine_profiles.py", line 40, in merge
    merged['capabilities'] = self.merge_capabilities(jsons, profile_names, api_version[1])
  File "/combine_profiles.py", line 118, in merge_capabilities
    self.promote_structs(feature, merged_features, True)
  File "/combine_profiles.py", line 278, in promote_structs
    for member in list(merged[promoted]):
KeyError: 'VkPhysicalDeviceVulkan13Features'
```

**Comment by christophe-lunarg** [comment]
I could not reproduce this issue, maybe it was fixed and we need more details
