### ISSUE TITLE
gen_profile_solution.py unable to deal with aliases 

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/Vulkan-Profiles#464]
The zink [profile](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/drivers/zink/VP_ZINK_requirements.json) has a reference to `VkPhysicalDeviceImagelessFramebufferFeatures` which is an alias for `VkPhysicalDeviceImagelessFramebufferFeaturesKHR`.

This makes the script abort : 
```
Registering profile 'VP_ZINK_gl21_baseline'
FATAL: Unexpected required struct 'VkPhysicalDeviceImagelessFramebufferFeatures' in profile 'VP_ZINK_gl21_baseline'
Traceback (most recent call last):
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 4392, in <module>
    profiles = VulkanProfiles.loadFromDir(registry, args.input, args.validate, schema)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2850, in loadFromDir
    VulkanProfiles.parseProfiles(registry, profiles, jsonData['profiles'], jsonData['capabilities'])
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2857, in parseProfiles
    profiles[name] = VulkanProfile(registry, name, data, caps)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2359, in __init__
    self.validate()
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2379, in validate
    self.validateStructDependencies()
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2384, in validateStructDependencies
    self.validateStructDependency(feature)
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 2410, in validateStructDependency
    Log.f("Unexpected required struct '{0}' in profile '{1}'".format(structName, self.name))
  File "vulkansdk-linux-x86_64-1.3.250.1/1.3.250.1/x86_64/share/vulkan/registry/gen_profiles_solution.py", line 1269, in f
    raise Exception(msg)
Exception: Unexpected required struct 'VkPhysicalDeviceImagelessFramebufferFeatures' in profile 'VP_ZINK_gl21_baseline'
```

**Comment by llandwerlin-intel** [comment]
It could be that `VkPhysicalDeviceImagelessFramebufferFeatures` only appeared in Vulkan 1.2 with the promotion.

In that case it would be similar to other zink profile issues (using 1.2 structs while only requesting 1.0.x API version).

But I'm not sure if alias are visible to previous API versions.
