### ISSUE TITLE
Python Script crashes in format merging

### ISSUE THREAD

**Issue by devshgraphicsprogramming** [KhronosGroup/Vulkan-Profiles#485]
I've created 3 profiles which actually pass validation against the JSON schema in the SDK.
(I've had to remove some descriptor buffer entries that were caused by buggy reporting of Vulkan Caps viewer)

Obviously I had them as `.json` but GitHub doesn't support attaching those
[amd.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402899/amd.txt)
[intel.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402900/intel.txt)
[nvidia.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402902/nvidia.txt)

But now the profile generation tool fails to merge them.
```
Building a Vulkan 1.3.250 profile
Traceback (most recent call last):
  File "gen_profiles_file.py", line 793, in <module>
    profile_merger.merge(jsons, profiles, profile_names, args.output_path, args.output_profile, args.profile_label, args.profile_desc, args.profile_api_version, profile_stage, profile_date, args.mode)
  File "gen_profiles_file.py", line 45, in merge
    merged['capabilities'] = self.merge_capabilities(jsons, profile_names, self.api_version)
  File "gen_profiles_file.py", line 168, in merge_capabilities
    self.merge_format_features(merged_formats, format, capability, prop_name, features)
  File "gen_profiles_file.py", line 294, in merge_format_features
    merged_formats[format][prop_name].remove(feature)
AttributeError: 'dict' object has no attribute 'remove'
```

This is both with `vk.xml` from SDK and latest from Vulkan-Headers repo.

**Comment by devshgraphicsprogramming** [comment]
Btw I was able to perform this operation on two generated profiles of MoltenVK
[desktop.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402912/desktop.txt)
[mobile.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402913/mobile.txt)

and got this out
[apple.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402915/apple.txt)

**Comment by devshgraphicsprogramming** [comment]
Btw I was able to perform this operation on two generated profiles of MoltenVK
[desktop.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402912/desktop.txt)
[mobile.txt](https://github.com/KhronosGroup/Vulkan-Profiles/files/12402913/mobile.txt)
