### ISSUE TITLE
Build of Vulkan-Profiles fails on Fedora 38

### ISSUE THREAD

**Issue by jgforbes** [KhronosGroup/Vulkan-Profiles#524]
-- Build files have been written to: /opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build
make: Entering directory '/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_layer.py", line 20, in <module>
    import gen_profiles_solution
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2022] Error 1
make[2]: *** [layer/CMakeFiles/VpLayer_generate.dir/build.make:70: layer/CMakeFiles/VpLayer_generate] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2023] Error 1
make[1]: *** [CMakeFiles/Makefile2:405: layer/CMakeFil-- Build files have been written to: /opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build
make: Entering directory '/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_layer.py", line 20, in <module>
    import gen_profiles_solution
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema-- Build files have been written to: /opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build
make: Entering directory '/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/build'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_layer.py", line 20, in <module>
    import gen_profiles_solution
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2022] Error 1
make[2]: *** [layer/CMakeFiles/VpLayer_generate.dir/build.make:70: layer/CMakeFiles/VpLayer_generate] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2023] Error 1
make[1]: *** [CMakeFiles/Makefile2:405: layer/CMakeFiles/VpLayer_generate.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:195: profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/all] Error 2
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopMax2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopMax2022] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: profiles/CMakeFiles/VpCreateDesktopMax2022.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

ModuleNotFoundError: No module named 'jsonschema'
Traceback (most recent call last):
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_file.py", line 22, in <module>
    import gen_profiles_solution
  File "/opt/DATA1/Downloads/jgf/1.3.268.0/source/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 28, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2022] Error 1
make[2]: *** [layer/CMakeFiles/VpLayer_generate.dir/build.make:70: layer/CMakeFiles/VpLayer_generate] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: profiles/CMakeFiles/VpCreateDesktopBaseline2022.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopBaseline2023] Error 1
make[1]: *** [CMakeFiles/Makefile2:405: layer/CMakeFiles/VpLayer_generate.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:195: profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/all] Error 2
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopMax2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopMax2022] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: profiles/CMakeFiles/VpCreateDesktopMax2022.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
es/VpLayer_generate.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:195: profiles/CMakeFiles/VpCreateDesktopBaseline2023.dir/all] Error 2
make[2]: *** [profiles/CMakeFiles/VpCreateDesktopMax2022.dir/build.make:71: profiles/CMakeFiles/VpCreateDesktopMax2022] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: profiles/CMakeFiles/VpCreateDesktopMax2022.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

However, jsonschema is installed.

**Comment by christophe-lunarg** [comment]
Hi, 
My guess, well that the error message, there is a problem with the installation of jsonschema module as the module can't be found but nothing that can be resolved on the project side.

**Comment by jgforbes** [comment]
I can run python from the command line and import jsonschema with no 
problems.
Is Vulkan-profiles building with a specific version of python other than 
the system version?

**Comment by christophe-lunarg** [comment]
The build instructions are here: https://github.com/KhronosGroup/Vulkan-Profiles/blob/main/BUILD.md
Python 3.7.2 is required.

**Comment by christophe-lunarg** [comment]
@jgforbes 
I created this PR: https://github.com/KhronosGroup/Vulkan-Profiles/pull/582
This will allow you to workaround this issue !
