### ISSUE TITLE
Profile generator fails to build profile for roadmap2024 features

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/Vulkan-Profiles#609]
I tried to update PROFILE.md for https://github.com/HansKristian-Work/vkd3d-proton/pull/1886. I built and installed generator libraries from roadmap2024 tag, and ran into:

```
Using VULKAN_PROFILE_PREFIX=/home/maister/.local.
Loading registry file: 'subprojects/Vulkan-Headers/registry/vk.xml'
WARNING: Ignoring member 'pCopyDstLayouts' in struct 'VkPhysicalDeviceHostImageCopyPropertiesEXT' containing ill-formed pointer to array
WARNING: Ignoring member 'pCopySrcLayouts' in struct 'VkPhysicalDeviceHostImageCopyPropertiesEXT' containing ill-formed pointer to array
Validating JSON profiles schema...
Loading profile file: 'VP_D3D12_VKD3D_PROTON_profile.json'
Validating profile file: 'VP_D3D12_VKD3D_PROTON_profile.json'
Traceback (most recent call last):
  File "/home/maister/.local/share/vulkan/registry/gen_profiles_solution.py", line 5317, in <module>
    input_profiles_files = VulkanProfilesFiles(registry, args.input, profiles_filenames, args.validate, schema)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maister/.local/share/vulkan/registry/gen_profiles_solution.py", line 3515, in __init__
    jsonschema.validate(json_root, schema)
  File "/usr/lib/python3.11/site-packages/jsonschema/validators.py", line 1312, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('VK_KHR_shader_maximal_reconvergence', 'VK_KHR_shader_quad_control' were unexpected)

Failed validating 'additionalProperties' in schema['properties']['capabilities']['additionalProperties']['properties']['extensions']:
    OrderedDict([('description',
                  'The block that stores required extensions.'),
                 ('type', 'object'),
                 ('additionalProperties', False),
                 ('properties',
                  OrderedDict([('VK_AMDX_shader_enqueue',
                                {'type': 'integer'}),
                               ('VK_AMD_buffer_marker',
                                {'type': 'integer'}),
                               ('VK_AMD_device_coherent_memory',
                                {'type': 'integer'}),
                               ('VK_AMD_display_native_hdr',

...

On instance['capabilities']['shader_model_67']['extensions']:
    {'VK_KHR_shader_maximal_reconvergence': 1,
     'VK_KHR_shader_quad_control': 1}
```

**Comment by christophe-lunarg** [comment]
Using https://www.jsonschemavalidator.net/ with the latest JSON schema and using the profiles file from the PR, I am getting two errors:
```
 Found 2 error(s)
 Message:
Property 'maximalReconvergence' has not been defined and the schema does not allow additional properties.
Schema path:
https://schema.khronos.org/vulkan/profiles-0.8.2-276.json#/definitions/VkPhysicalDeviceShaderMaximalReconvergenceFeaturesKHR/additionalProperties
Message:
Property 'quadControl' has not been defined and the schema does not allow additional properties.
Schema path:
https://schema.khronos.org/vulkan/profiles-0.8.2-276.json#/definitions/VkPhysicalDeviceShaderQuadControlFeaturesKHR/additionalProperties
```

**Comment by christophe-lunarg** [comment]
I am hitting an issue when building with the fixed profile...
```
5>FATAL: Unexpected required struct 'VkPhysicalDeviceConservativeRasterizationPropertiesEXT' in profile 'VP_D3D12_FL_12_2_baseline'
```
Investigating

**Comment by christophe-lunarg** [comment]
So, it looks like it's the splitting of capabilities in `properties` and `features` that results into the issue with `VkPhysicalDeviceConservativeRasterizationPropertiesEXT`.

```
        "fl_12_1_features": {
            "extensions": {
                "VK_EXT_conservative_rasterization": 1
            }
        },
```
and 
```
        "fl_12_2_features": {
            "properties": {
                "VkPhysicalDeviceConservativeRasterizationPropertiesEXT": {
                    "degenerateTrianglesRasterized": true,
                    "fullyCoveredFragmentShaderInputVariable": true
                },
                "VkPhysicalDeviceFragmentShadingRatePropertiesKHR": {
                    "fragmentShadingRateNonTrivialCombinerOps": true
                }
            },
```
I am actually wonder whether it's expected that the extension is required for `fl_12_1_features` and the properties set for `fl_12_2_features`. It could be legit.

If I add:
```
        "fl_12_2_features": {
            "extensions": {
                ...
                "VK_EXT_conservative_rasterization": 1
            },
            "properties": {
                "VkPhysicalDeviceConservativeRasterizationPropertiesEXT": {
                    "degenerateTrianglesRasterized": true,
                    "fullyCoveredFragmentShaderInputVariable": true
                },
                "VkPhysicalDeviceFragmentShadingRatePropertiesKHR": {
                    "fragmentShadingRateNonTrivialCombinerOps": true
                }
            },
```

The error doesn't happen anymore... Not sure exactly how to resolve this. This is at least a workaround.

It's most likely because of the ordering of loading things. Investigating.

**Comment by christophe-lunarg** [comment]
So I think it's valid to consider that the capabilities block is not defined correctly because blocks can be check for support individually.

So if an application (that could be VKD3D_proton itself) were using:
```
VkResult vpGetPhysicalDeviceProfileVariantsSupport(
    VkInstance                      instance,
    VkPhysicalDevice                physicalDevice,
    const VpProfileProperties*      pProfile,
    VkBool32*                       pSupported,
    uint32_t*                       pPropertyCount,
    VpBlockProperties*              pProperties);
```
Ideally, the block that declares the property but not the extension should ideally be returned as unsupported.

So, I think, I'll resolve with making sure the error message state the missing extension.

**Comment by christophe-lunarg** [comment]
And the fixed profiles file:
[VP_D3D12_VKD3D_PROTON_profile.json](https://github.com/KhronosGroup/Vulkan-Profiles/files/14284933/VP_D3D12_VKD3D_PROTON_profile.json)

**Comment by HansKristian-Work** [comment]
Still doesn't work for me, sadly.

I built and installed the latest profiles commit, but I'm still getting:

```
On instance['capabilities']['shader_model_67']['extensions']:
    {'VK_KHR_shader_maximal_reconvergence': 1,
     'VK_KHR_shader_quad_control': 1}
```

**Comment by HansKristian-Work** [comment]
nvm, wrong header repo was used.
