### ISSUE TITLE
gen_profiles_solution.py won't work with --debug if no debug folder?

### ISSUE THREAD

**Issue by trevordblack** [KhronosGroup/Vulkan-Profiles#617]
When I run the `gen_profiles_solution.py` with the `--debug` flag it crashes

```
tdb@tdb:~/Vulkan-Profiles$ python3 scripts/gen_profiles_solution.py --debug  --registry ~/Vulkan/xml/vk.xml --input ~/.../profiles/ --output-library-inc . --output-library-src .
Loading registry file: '...'
Loading profile file: 'VP_ANDROID_baseline_2021.json'
Registering profile 'VP_ANDROID_baseline_2021'
Required profiles by the VP_ANDROID_baseline_2021 profile: None
Required capabilities blocks by the VP_ANDROID_baseline_2021 profile:
- VP_ANDROID_baseline_2021::baseline
Generating '/.../Vulkan-Profiles/vulkan_profiles.h'...
Generating '/.../Vulkan-Profiles/vulkan_profiles.cpp'...
Generating '/.../Vulkan-Profiles/vulkan_profiles.hpp'...
Generating '/.../Vulkan-Profiles/debug/vulkan_profiles.h'...
Traceback (most recent call last):
  File "/usr/local/google/home/vantablack/VulkanWork/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 5324, in <module>
    generator.generate(args.output_library_inc + '/debug', args.output_library_src + '/debug')
  File "/usr/local/google/home/vantablack/VulkanWork/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 3551, in generate
    self.generate_h(outIncDir)
  File "/usr/local/google/home/vantablack/VulkanWork/Vulkan-Profiles/scripts/gen_profiles_solution.py", line 3559, in generate_h
    with open(fileAbsPath, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/.../Vulkan-Profiles/debug/vulkan_profiles.h'
```

Was I required to specify the location of the debug output location?
Is this because both debug and non-debug are named `vulkan_profiles.**` and the concern is overriding the other?

If I'm asking for debug, I really only care about the debug files.

What would you recommend me do in the future?

**Comment by christophe-lunarg** [comment]
Hi Trevor,
I added an option to set the generation configuration, which won't add the `debug` subdirectory and it works this way:
```
gen_profiles_solution.py --config debug              # With debug messages
gen_profiles_solution.py --config release             # Without debug messages, by default
```

If you are only interested in the header-only library, you no longer require `--output-library-src `

Is that good enough for you?
