### ISSUE TITLE
gen_profiles_solution.py failing to generate solution

### ISSUE THREAD

**Issue by llandwerlin-intel** [KhronosGroup/Vulkan-Profiles#684]
```
$ python3 scripts/gen_profiles_solution.py --registry vk.xml --api vulkan --input profiles --output-library-filename lib --output-library-src lib.c --output-library-inc lib.h
Loading registry file: 'vk.xml'
Loading profile file: 'VP_ANDROID_baseline_2022.json'
Loading profile file: 'VP_LUNARG_desktop_baseline_config.json'
Loading profile file: 'VP_LUNARG_desktop_baseline.json'
Loading profile file: 'VP_KHR_roadmap.json'
Loading profile file: 'VP_LUNARG_minimum_requirements.json'
Loading profile file: 'VP_ANDROID_15_minimums.json'
Loading profile file: 'VP_ANDROID_baseline_2021.json'
Registering profile 'VP_ANDROID_baseline_2022'
Required profiles by the VP_ANDROID_baseline_2022 profile: None
Required capabilities blocks by the VP_ANDROID_baseline_2022 profile:
- VP_ANDROID_baseline_2022::baseline
Traceback (most recent call last):
  File "scripts/gen_profiles_solution.py", line 5999, in <module>
    input_profiles_files = VulkanProfilesFiles(registry, args.input, profiles_filenames, args.validate, schema)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "scripts/gen_profiles_solution.py", line 4194, in __init__
    self.parseProfiles(registry, json_file_data['profiles'], json_file_data['capabilities'])
                                                             ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'capabilities'
```

**Comment by christophe-lunarg** [comment]
Your command line fail because you are including a file which is not a profile. 'VP_LUNARG_desktop_baseline_config.json'

I'll move it out of the way to avoid this issue in the future.
